### ISSUE TITLE
lfspkg --list command not working

### ISSUE THREAD

**Issue by chinnadas** [KeithDHedger/LFSPkgBuilds#2]
Hi sir,
 i have build LFS/BLFS with Xfce4 Desktop using lfspkg but when i  list the packages using lfspkg --list command getting below
lfspkg --list
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
Nothing by that name :(

**Comment by KeithDHedger** [comment]
you need to supply a package name, eg lfspkg --list kkedit

K

Sent from MailDroid

-----Original Message-----

**Comment by KeithDHedger** [comment]
please read the man page!
