### ISSUE TITLE
Error trying to build xorg-meta

### ISSUE THREAD

**Issue by zhuhualong** [KeithDHedger/LFSPkgBuilds#5]
I recently completed the LFS v11.0 book build and added your LFSPkg software.  I used your HowTo and was trying to install xorg and I encountered this message.

"ERROR  Version of build script /LFSPkgBuildScripts/system/openssl/openssl.LFSBuild is to low for dependency OpenSSL-1.1.1"

I have that version of OpenSSL already installed on the system.

Any ideas to resolve this?
Thanks!

**Comment by KeithDHedger** [comment]
the pkgs are for lfs 10.1 you will have to manually adjust the version number in some scripts  openssl changes frequently check the version in the PkgVersions file in LFSScripts/*/ as this is auto generated let me know what happens also whether you are building sysv, systemd etc

**Comment by zhuhualong** [comment]
I am using systemd.  I have tried adjusting the versions in PkgVersions to the same I have, including subversions.  I have even tried hardcoding the version number in the scripts  without success.  That is why I ask for your help.  I am at a loss to know what to do.  I teach lfs as a class to teach the students the true learning of linux after I teach them the basics.  LFS has no real package management and I have read good reviews and real input about your software.   I know a simple version difference can affect your solution.  I have tried debian apt and arch pacman without success.  I want this to work for the benefit of spreading the word of linux as a solution to the evil Windows.  BTW... I'm an American living
 in China.  :)

**Comment by KeithDHedger** [comment]
if you teach linux you should be able to debug a bash script, but  be that as it may this meta script works fine my end have you tried a git pull, have you installed and set up lfpkg properly, have you set the LFSVERSION to 10.1? again these scripts are for lfs version 10.1 not 11, try running through the meta script dependenceis and run each script manually, try recloning this repo and start with fresh scripts if all else fails tar up your complete LFSPkgBuilds folder and email it to me and I will see what I can do.

**Comment by zhuhualong** [comment]
After everything, I cloned my host again and did a fresh install of LFSPkgBuilds and then simply changing my LFS version to 10.1, as you suggested, it worked.  Thanks again for your help.  

從我的 iPhone 4s 傳送

**Comment by KeithDHedger** [comment]
yur welcome
